export default {
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDERS_REPOSITORY: 'ORDERS_REPOSITORY',
  ADDRESSES_REPOSITORY: 'Addresses_REPOSITORY',
  NOTIFICATION_REPOSITORY: 'NOTIFICATION_REPOSITORY',
};
